---
name: go-run
run-name: go-run
on:
  - push
jobs:
  go-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
        with:
          go-version: "1.20.3"
      - run: go run main.go
