---
name: hello
run-name: hello
on:
  - push
jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/say-hello"
        with:
          name: taro
