---
name: Print github contexts
run-name: Print github contexts
on:
  - push

jobs:
  print_github_contexts:
    runs-on: ubuntu-22.04
    env:
      TZ: "Asia/Tokyo"

    steps:
      - name: Print Github Contexts
        run: |
          echo "github.action ${{github.action}}"
          echo "github.action_path ${{github.action_path}}"
          echo "github.actor ${{github.actor}}"
          echo "github.base_ref ${{github.base_ref}}"
          echo "github.event ${{github.event}}"
          echo "github.event_name ${{github.event_name}}"
          echo "github.event_path ${{github.event_path}}"
          echo "github.head_ref ${{github.head_ref}}"
          echo "github.job ${{github.job}}"
          echo "github.ref ${{github.ref}}"
          echo "github.repository ${{github.repository}}"
          echo "github.repository_owner ${{github.repository_owner}}"
          echo "github.run_id ${{github.run_id}}"
          echo "github.run_number ${{github.run_number}}"
          echo "github.sha ${{github.sha}}"
          echo "github.token ${{github.token}}"
          echo "github.workflow ${{github.workflow}}"
          echo "github.workspace ${{github.workspace}}"
